name: flutter_map_dragmarker
description: Dragmarker class for flutter_map

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_map: ^0.13.1
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true