name: flutter_map_dragmarker
description: Dragmarker class for flutter_map

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_map:
    git:
      url: https://github.com/AttalliAyoub/flutter_map.git
  latlong: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true